### ISSUE TITLE
unicode string is cut off by two characters

### ISSUE THREAD

**Issue by erf** [Blimster/resp_client#10]
My issue #8 now return with unicode characters but is lacking the two last characters!

That is this:

```
  final resrult = await commands.set('someKey', 'abcØØhehe');
  final value = await commands.get('someKey');
```

Returns:

```
abcØØhe
```

and not

```
abcØØhehe
```

Maybe a unit code test would be an good idea.

**Comment by Blimster** [comment]
I released new version 0.2.1 and 1.1.1. 

The issue is fixed an I added some tests ;-).
