### ISSUE TITLE
Get number of keys in db

### ISSUE THREAD

**Issue by erf** [Blimster/resp_client#11]
I'd like to get the number of keys in my db, i know there is s `scan` method but the `ScanResult._keys` is private, so i can't it. Also i tried to set `pattern: '*'` but that crashed. Not too familiar with `redis` but i thought that would give me all keys?

My problem would be solved if  [DBSIZE](https://redis.io/commands/dbsize) or  [INFO](https://redis.io/commands/INFO) was added to `RespCommands`. But maybe there already is a way to check for this?

**Comment by erf** [comment]
I figured i could use: 

```
    final sizeResult = await fakkt.redis.client.writeArrayOfBulk(['DBSIZE']);
    final size = sizeResult.payload;
```

But maybe this could be a nice command helper like: `command.dbsize`

**Comment by Blimster** [comment]
I released new version 0.2.1 and 1.1.1. 

I added the commands `dbsize` and `info`. Also added getters for `cursor` and `keys` to `ScanResult` in version 1.1.1 (the getters were accidently lost when migrating to null safety). Crash when using a pattern in command `scan` is also fixed.

Yes, you can always use the low level API if a command is missing. Adding a missing command is not that difficult by way. Maybe next time you create a PR. I would be pleased.

**Comment by erf** [comment]
Grest work on the package! I can try to make a PR if i see a need. Do you want me to make an issue first still?

**Comment by Blimster** [comment]
Not really sure, but I think a PR is an issue, too. Thus, you need no extra issue first.
