### ISSUE TITLE
Transaction support

### ISSUE THREAD

**Issue by domesticmouse** [Blimster/resp_client#12]
Please add support for MULTI, EXEC, DISCARD and WATCH commands.

[Redis transaction topic](https://redis.io/topics/transactions) documentation

**Comment by Blimster** [comment]
Hi. I looked into it. This is a bigger refactoring, because commands executed in a transaction return other values as in "normal" mode.

The refactoring will took a while. Meanwhile, try the low-level API described here: https://github.com/Blimster/resp_client#use-low-level-api

**Comment by domesticmouse** [comment]
We are looking at options for migrating the `dart-services` project to null safety. Our current Dart redis client Dartis isn't null safe: https://github.com/jcmellado/dartis/issues/34

**Comment by Blimster** [comment]
I released v1.2.0 of resp_client on pub.dev with support for the transaction-related commands. I added an example for the usage. Hope that helps.
