### ISSUE TITLE
How do I pass in the password?

### ISSUE THREAD

**Issue by neelkamath** [Blimster/resp_client#3]
This code:
```dart
void main() async {
  var client = RespClient(await connectSocket(
      'ec2-18-209-253-27.compute-1.amazonaws.com',
      port: 38819,));
  var commands = RespCommands(client);
  print(await commands.clientList());
}
```
produces this error:
```
Unhandled exception:
Bad state: error message from server: NOAUTH Authentication required.
```

Feel free to use the included Redis URL, it's just a test app I have up. The password is `pb96f89815857c41b3724d9ee59be14ee5e92c2da94f76350abf8b0a5f45f8823`.

**Comment by Blimster** [comment]
Hi, I published version 0.1.3 with the AUTH command implemented. A test with your provided server was successful.
